#!/bin/bash
cd /home/ec2-user/node-website
curl -sL https://rpm.nodesource.com/setup_9.x | bash -
yum install -y nodejs
curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
yum install yarn
yarn install forever -g
